### ISSUE TITLE
The link cannot be clicked after updating to 0.2.0 version

### ISSUE THREAD

**Issue by legend053** [tokuhirom/obsidian-advanced-links-lugin#14] opened 2021-05-12 23:23 UTC
After the newest update, the link at the bottom is not clickable anymore.

**Comment by tokuhirom** [comment] 2021-05-13 00:29
hmm... I can't reproduce it. did you restart the obsidian app?

**Comment by tokuhirom** [comment] 2021-05-19 04:54
I can't reproduce this. I close this issue at the moment. If you can got this issue again, please re-open this issue.

**Closed as completed by tokuhirom** 2021-05-19 04:54 UTC
